name: biopyassistantenv
channels:
  - defaults
dependencies:
  - langchain
  - unstructured # Document loading
  - chromadb # Vector storage
  - openai # For embeddings
  - tiktoken # For embeddings
  - black # For code formatting
  - loguru # For logging
  - streamlit # For web app testing